version: '3'

services:
  frontend:
    image: node:16 
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build:/usr/share/nginx/html:ro
    ports:
      - "80:80"
